parameters:
#    acme_store.example.class: Acme\StoreBundle\Example

services:
#    acme_store.example:
#        class: %acme_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    sonata.admin.product:
        class: Acme\StoreBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Продукты", label: "Продукты" }
        arguments:
            - ~
            - Acme\StoreBundle\Document\Product
            - ~
        calls:
            - [ setTranslationDomain, [AcmeStoreBundle]]